#!/usr/bin/env bash

statuses=$(awk -F"[[]" '/\[[a-z]*\]/{ gsub(/\]/,"");print $3 }' <(amixer -D pulse get Capture))

out="$LABEL"
for status in $statuses; do 
  if [ $status == 'on' ]; then
    out+=" ON "
  elif [ $status == 'off' ]; then
    out+=" OFF "
  fi
done

echo $out
