#!/usr/bin/bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bin,i3,i3blocks,kitty,nvim,rofi,tmux,zsh,xresources"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
