#!/bin/bash

# QT5 fix
export QT_QPA_PLATFORMTHEME="qt5ct"

# Sway + wlroots support (https://github.com/flameshot-org/flameshot/blob/master/docs/Sway%20and%20wlroots%20support.md)
export _JAVA_AWT_WM_NONREPARENTING=1
export SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
#export GDK_BACKEND='wayland,x11'
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM='wayland;xcb'
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export WLR_NO_HARDWARE_CURSORS=0
export GTK_USE_PORTAL=1

exec sway
